input {
  tcp {
    mode => "server"
    host => "0.0.0.0"
    port => 4560
    codec => json_lines
    type => "info"
  }
}
filter {}
output {
  elasticsearch {
      action => "index"
      hosts => ["http://elasticsearch:9200"]  # 容器网络内通过服务名访问
      user => "elastic"                       # es用户名
      password => "${ELASTIC_PASSWORD}"       # es密码
      index => "xybjz-log-%{+YYYY.MM.dd}" #索引名
      manage_template => false
    }
}
